--Insercao de LISTA DE JOGOS
INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');

--Insercao de jogos no banco
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'Mass Effect 3 is the epic conclusion to Commander Shepard''s story, where the Reapers invade Earth, forcing the galaxy to unite against this overwhelming threat.', 'Mass Effect is a military science fiction media franchise created by Casey Hudson. The franchise depicts a distant future where humanity and several alien civilizations have colonized the galaxy using technology left behind by advanced precursor civilizations.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'Red Dead Redemption 2 is a sprawling, story-driven action-adventure game set in a fictionalized rendition of the American West in 1899.', 'Red Dead Redemption 2 is a 2018 action-adventure game set in a fictionalized representation of the American West in 1899. Players experience the decline of the Wild West era through the eyes of Arthur Morgan, an outlaw and member of the Van der Linde gang, as they navigate a world of lawmen, rival gangs, and the changing landscape of the American frontier. The game features a vast open world, a compelling story, and a focus on character development and player choice. ');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'The Witcher 3: Wild Hunt is an open-world action RPG where players take on the role of Geralt of Rivia, a monster hunter, as he searches for his adopted daughter, Ciri, who is being pursued by the Wild Hunt, a spectral force threatening to end the world.', 'is an open-world action RPG where players take on the role of Geralt of Rivia, a monster hunter, as he embarks on a personal quest to find his adopted daughter, Ciri, while also dealing with the threat of the Wild Hunt and the impending White Frost');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', ' is an action-adventure game set in 14th-century Japan, where you play as a disgraced, one-armed shinobi (ninja) tasked with rescuing a young lord and exacting revenge.', 'is a third-person action-adventure game developed by FromSoftware, the creators of the Dark Souls series. Set in 14th-century Japan, the game follows a disgraced shinobi named Wolf, tasked with rescuing his kidnapped lord and exacting revenge on his enemies. The game emphasizes stealth, exploration, and intense, strategic combat, with a particular focus on boss battles. ');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Ghost of Tsushima is an open-world action-adventure game set during the first Mongol invasion of Japan in 1274!', ' is an open-world action-adventure game set in feudal Japan during the first Mongol invasion. Players take on the role of Jin Sakai, a samurai who must choose between upholding his samurai code or adopting more stealthy and unconventional tactics to protect his island home. The game features a vast open world to explore, dynamic combat, and a story that explores themes of honor, sacrifice, and the conflict between tradition and survival. ');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'It''s known for introducing Yoshi, the rideable dinosaur, and includes a variety of levels, secret areas, and two-player modes.', 'Super Mario World, known in Japan as Super Mario World: Super Mario Bros. 4,[a] is a 1990 platform game developed by Nintendo EAD and published by Nintendo for the Super Nintendo Entertainment System (SNES). The player controls Mario on his quest to save Princess Peach and Dinosaur Land from the series'' antagonist Bowser and the Koopalings. The gameplay is similar to that of earlier Super Mario games; players control Mario through a series of levels in which the goal is to reach the goalpost at the end. Super Mario World introduces Yoshi, a ridable dinosaur who can eat enemies and spit some of them out as projectiles.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, '2D Action Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Hollow Knight is a 2D action-adventure game where you explore the fallen insectoid kingdom of Hallownest, battling creatures and uncovering its secrets.', 'Hollow Knight is a 2017 action-adventure Metroidvania game developed by Team Cherry. Players explore the fallen insect kingdom of Hallownest, controlling a silent knight on a quest to uncover its mysteries and battle a supernatural plague. The game is known for its hand-drawn art style, atmospheric soundtrack, challenging combat, and expansive world. ');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Ori and the Blind Forest" is a visually stunning 2D platformer where players control Ori, a young spirit guardian, on a quest to restore a dying forest', 'Ori and the Blind Forest" is a visually stunning 2D Metroidvania platformer developed by Moon Studios. It tells the story of Ori, a guardian spirit, who must embark on a quest to restore the dying forest of Nibel. The game features a compelling narrative, beautiful hand-painted artwork, and a fully orchestrated score. Players explore a vast world, gaining abilities and navigating challenging platforming sequences while battling enemies and solving puzzles.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Run and Gun', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Cuphead is a classic run-and-gun action game, heavily focused on boss battles, with a unique 1930s cartoon art style.', 'Cuphead is a classic run and gun action game heavily focused on boss battles. Inspired by cartoons of the 1930s, the visuals and audio are painstakingly created with the same techniques of the era: traditional hand drawn cel animation, watercolor backgrounds, and original jazz recordings.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Sonic the Hedgehog is a blue, anthropomorphic hedgehog known for his incredible speed, often described as being faster than the speed of sound.', 'Sonic CD is a 2D side-scrolling platformer, similar to the original Sonic the Hedgehog, where players control Sonic on a quest to stop Doctor Robotnik (also known as Dr. Eggman) from taking over Little Planet. A key feature of Sonic CD is its time travel mechanic, allowing players to explore past, present, and future versions of each level, each with distinct visuals and music. ');


--Insercao de associacoes de jogos, como lista, id e sua posicao
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);